### PR TITLE
tulip: set 16GB variants

### PR DESCRIPTION
**Pull request by alviteri**
override 8GB config in kanuti-common

### CODE REVIEW

**Comment by pablomh** [comment]
Does it work for you this way? IIRC when I tested this approach it didn't work :(

**Comment by alviteri** [comment]
Are you sure ?

**Comment by jerpelea** [comment]
this should be the proper aproach

**Comment by pablomh** [comment]
It doesn't seem to work for me:

```
creating userdata.img...
Running:  mkuserimg.sh -s /tmp/tmpmNaMP2/data /tmp/tmpFTniRE ext4 data 4399808512 -T 1230768000 -L data /tmp/targetfiles-8QBFDA/META/file_contexts.bin
make_ext4fs -s -T 1230768000 -S /tmp/targetfiles-8QBFDA/META/file_contexts.bin -L data -l 4399808512 -a data /tmp/tmpFTniRE /tmp/tmpmNaMP2/data
Creating filesystem with parameters:
    Size: 4399808512
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8144
    Inode size: 256
    Journal blocks: 16783
    Label: data
    Blocks: 1074172
    Block groups: 33
    Reserved block group size: 263
Created filesystem with 11/268752 inodes and 35769/1074172 blocks
Running:  simg2img /tmp/tmpFTniRE /tmp/unsparse_tmpFTniRE
```

**Comment by oshmoun** [comment]
maybe this would work if the value in kanuti would only be set if not previously defined?
I think the operator is ?=

**Comment by alviteri** [comment]
Obeida I don't think so

https://github.com/sonyxperiadev/device-sony-loire/blob/n-mr1/PlatformConfig.mk#L54
https://github.com/sonyxperiadev/device-sony-kugo/blob/n-mr1/BoardConfig.mk#L22

**Pull request merged**
